export enum Emotion {
    tristeza = 'Tristeza',
    ansiedade = 'Ansiedade',
    medo = 'Medo',
    raiva = 'Raiva',
    culpa = 'Culpa',
    vergonha = 'Vergonha',
    frustração = 'Frustração',
    desespero = 'Desespero',
    solidão = 'Solidão',
    nojo = 'Nojo',
    desânimo = 'Desânimo',
    irritação = 'Irritação',
    inveja = 'Inveja',
    decepção = 'Decepção',
    ciúme = 'Ciúme',
    estresse = 'Estresse',
    pânico = 'Pânico',
    outro = 'Outro',
}