export enum Behavior {
    evacaoAfastamento = 'Evasão/Afastamento: Evitar situações ou pessoas.',
    isolamento = 'Isolamento: Se isolar socialmente ou emocionalmente.',
    confrontoAgressao = 'Confronto/Agressão: Confrontar ou ser agressivo em relação a outros.',
    choro = 'Choro: Responder à situação com choro.',
    procrastinacao = 'Procrastinação: Adiar ou evitar tarefas.',
    comportamentoCompulsivo = 'Comportamento Compulsivo: Comer compulsivamente, fazer compras excessivas, etc.',
    autocritica = 'Autocrítica: Ficar se criticando internamente.',
    buscaDeReafirmacao = 'Busca de Reafirmação: Buscar aprovação ou validação dos outros.',
    autocuidadoNegligente = 'Autocuidado Negligente: Negligenciar o cuidado pessoal, como alimentação ou higiene.',
    usoDeSubstancias = 'Uso de Substâncias: Recorrer ao uso de álcool, drogas ou outros.',
    comportamentoPerfeccionista = 'Comportamento Perfeccionista: Tentar realizar tudo com perfeição extrema.',
    comportamentoPassivoAgressivo = 'Comportamento Passivo-Agressivo: Expressar raiva de forma indireta ou passiva.',
    fugaParaAtividadesDistracoes = 'Fuga para Atividades/Distrações: Fuga para atividades como assistir TV em excesso, navegar na internet, etc.',
    autoagressao = 'Autoagressão: Ferir-se ou agir de forma prejudicial a si mesmo.',
    defesaExcessiva = 'Defesa Excessiva: Justificar-se ou se defender de forma exagerada.',
    culparOsOutros = 'Culpar os Outros: Colocar a culpa em outras pessoas pelas dificuldades.',
    outro = 'Outro',
}